# -*- coding: utf-8 -*-
"""Data_Augmentation_동의어 & 유의어 교체.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHZWhM53WMV2zMze22Gbpn5ENGKZp57w
"""

!pip install konlpy

!pip install nltk

from konlpy.tag import Komoran
from nltk.corpus import wordnet
import random

import nltk
nltk.download('wordnet')

def get_synonyms(word):
    """
    주어진 단어의 동의어(유의어)를 가져옵니다.
    """
    synonyms = []
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.append(lemma.name())
    if word in synonyms:
        synonyms.remove(word)
    return list(set(synonyms))

def replace_with_synonym(text, p=0.5):
    """
    주어진 텍스트에서 일부 단어를 랜덤하게 동의어로 교체합니다.
    """
    words = Komoran().morphs(text)
    new_words = []
    for word in words:
        if random.uniform(0, 1) < p:
            synonyms = get_synonyms(word)
            if synonyms:
                new_words.append(random.choice(synonyms))
            else:
                new_words.append(word)
        else:
            new_words.append(word)
    return ' '.join(new_words)

# 텍스트 데이터
text = "아니 유의어처리 왜 안되냐구~"

# 데이터 증강 적용
augmented_data = []

# 원본 데이터 추가
augmented_data.append(text)

# 동의어 교체
augmented_data.append(replace_with_synonym(text))

# 결과 출력
for data in augmented_data:
    print(data)